### ISSUE TITLE
Make status confirmation less noisy

### ISSUE THREAD

**Issue by limi** [benadida/teamstatus#15]
When reporting that the status was successful, it would be less noisy if it did that in a /msg to the individual instead of to the channel:

```
<status> limi: status recorded at http://teamstat.us/#show/irc.mozilla.org/ux/limi/2731
```

…is a bit redundant, as the channel will see what I just said to the status bot anyway. Sending it in a /msg instead makes more sense to me, at least. :)

**Comment by gregglind** [comment]
At least for us, it seems like having this level of noisy is helping spur adoption.

**Comment by benadida** [comment]
I think I agree with @gregglind that the noise helps point folks to the web page...

**Comment by benadida** [comment]
@limi closing this as per above, but tell me if this is stopping you from using teamstatus. Btw, some fun updates coming soon.
