### ISSUE TITLE
schedule status requests

### ISSUE THREAD

**Issue by groovecoder** [benadida/teamstatus#21]
In #mdndev we try to have a "standup" at 10am PT. It would be nice if the status bot would keep a list of people to ping like so:

craigcook: groovecoder: jsocol: lorchard: retornam: ubernostrum: standup!

**Comment by lloyd** [comment]
hmmm...  notifications.  @benadida this feels to me like it may be pushing the scope a bit.  what do you think?

**Comment by benadida** [comment]
I think beyond nagging folks as in issue #24 , @lloyd is right I don't want to push scope too far.
