### ISSUE TITLE
url for channel should show all users in that channel

### ISSUE THREAD

**Issue by gregglind** [benadida/teamstatus#22]
Ex:

```
 http://teamstat.us/#show/irc.mozilla.org/ur/
```

should show everyone in #ur.

Is this the right expectation?

**Comment by benadida** [comment]
I figured showing only those who have added status makes more sense, since some folks might lurk.

**Comment by benadida** [comment]
@gregglind I'm closing this as I don't anticipate fixing this anytime soon, please reopen if you think this is important.
