### ISSUE TITLE
don't incite botfights.

### ISSUE THREAD

**Issue by lloyd** [benadida/teamstatus#26]
On this fine day, qatestbot and teamstatus got in a fight:

http://irclog.gr/#show/irc.mozilla.org/identity/102463

for gods sakes man!  there are children around!

**Comment by benadida** [comment]
I love it when people say that Terminator-style doomsday scenarios are crazy. We can't even stop stupid irc bots from fighting.

**Comment by lmorchard** [comment]
We get the same thing on #mdndev between `status` and `jenkins`, which are probably much the same bots. Maybe a blacklist for bots? Maybe require a specific privmsg from a user to "opt-in" & whitelist a particular nick?

**Comment by ncalexan** [comment]
Ditto for `status` and `jenkins` in `#androidsync`.
